config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  devise_for :users
  resources :posts do
    resources :comments
  end
  # get '/:id/comment/new', to: 'posts#new_comment', as: 'new_comment'
  # post '/:id/comment', to: 'posts#create_comment'
  # get '/:id/comment/:id/edit', to: 'posts#edit_comment', as: 'edit_comment'
  # put '/:id/comment/:id', to: 'posts#update_comment'
  # patch '/:id/comment/:id', to: 'posts#update_comment'
  # get '/comment/:id', to: 'posts#destroy_comment', as: 'destroy_comment'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :description, presence: true, allow_blank: false
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :description, presence: true, allow_blank: false
  belongs_to :user
  accepts_nested_attributes_for :comments, reject_if: :all_blank, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :username, uniqueness: true
  accepts_nested_attributes_for :comments, reject_if: :all_blank, allow_destroy: true
  attr_writer :login
  # accepts_nested_attributes_for :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def login
    @login || username || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value', { value: login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up, keys: %i[email username password password_confirmation remember_me]
    devise_parameter_sanitizer.permit :sign_in, keys: %i[login password]
    devise_parameter_sanitizer.permit :account_update, keys: %i[email username password password_confirmation remember_me]
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def edit
    @post = Post.find_by(id: params[:post_id])
    @comments = @post.comments
    @comment = Comment.find_by(id: params[:id])
  end

  def update
    @post = Post.find_by(id: params[:post_id])
    @comment = Comment.find_by(id: params[:id])
    if @comment.user_id == current_user.id
      if @comment.update(comment_params)
        redirect_to post_path(@post.id)
      else
        if @comment.errors.any?
          @comment.errors.full_messages
        end
        render :edit
      end
    end
  end

  def show
    @comment = Comment.find_by(id: params[:id])
  end

  def destroy
    @post = Post.find_by(params[:post_id])
    @comment = Comment.find_by(id: params[:id])
    if @comment.user_id == current_user.id
      @comment.destroy
    end
    redirect_to post_path(@post.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:description, :post_id, :user_id, :_destroy)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    if @post.save
      redirect_to posts_path
    else
      if @post.errors.any?
        @post.errors.full_messages
      end
      render :new
    end
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      if @post.errors.any?
        @post.errors.full_messages
      end
      render :edit
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    @comments = @post.comments
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:description, :user_id,
                                 comments_attributes: %i[id description post_id user_id _destroy])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/edit.html.erb
<% if @comment.errors.any? %>
  <% @comment.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>
<% if @comment.present? %>
<%= form_for @comment, url: post_comment_path(@post.id, @comment.id) do |f| %>
    <%= f.label :description, "Comment" %>
    <br/>
    <%= f.text_field :description %>

    <br/>
    <%= f.submit %>
  <% end %>
<% else %>
<h2>Record not found</h2>
<% end %>

app/views/comments/show.html.erb
<% if @comment.present? %>
  <h3><%= @comment.description %></h3>
  <% else %>
  <h3>Record not found</h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseAuthNew</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <br/>

    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </p>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_comment_fields.html.erb
<div class="nested-fields">
  <%= f.label :description, "Comment" %><br/>
  <%= f.text_field :description %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= link_to_remove_association 'Delete', f %>
</div>

app/views/posts/_comment_form.html.erb
<%= form_for @post, url: url do |form| %>
    <div>
      <br>
      <%= link_to_add_association "Add Comment", form, :comments %>
    </div>
  </div>
  <%= form.submit %>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post, url: url do |form| %>
  <%= form.label :description, "Post :- " %>
  <%= form.text_field :description %><br/><br/>
  <div>
    <%= form.fields_for :comments do |t| %>
      <%= render "comment_fields", :f => t %>
    <% end %>
    <div>
      <br>
      <%= link_to_add_association "Add Comment", form, :comments %>
    </div>
  </div>
  <%= form.submit %>
<% end %>

app/views/posts/edit.html.erb
<% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
<% end %>
<% if @post.user_id === current_user.id %>
  <h1>Edit Post</h1>
  <%= render "form", url: "/posts/#{@post.id}" %>
<% else %>
  <h1>New Comment</h1>
  <%= render "comment_form", url: "/posts/#{@post.id}" %>
<% end %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<h2><%= link_to "New Post", new_post_path %></h2>
<table>
  <tr>
    <th>S.No.</th>
    <th>Post</th>
    <th>Actions</th>
  </tr>
  <% @posts.each.with_index(1) do |post, i| %>
    <tr>
      <td><%= i %></td>
      <td><%= post.description %></td>
      <td><%= link_to "Show", post_path(post.id) %></td>
      <td><%= link_to "Comment", edit_post_path(post.id) %></td>
      <% if post.user_id == current_user.id %>
        <td><%= link_to "Edit", edit_post_path(post.id) %></td>
        <td><%= link_to "Delete", post_path(post.id), method: 'delete', data: { confirm: "Are you Sure" } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>
<h1>New Post</h1>
<!--<h3><%#= link_to "Add Comment", new_comment_path(@post.id) %></h3>-->
<%= render "form", url: "/posts" %>

app/views/posts/show.html.erb
<li><%= @post.description %></li>
<table>
<ul>
  <% @comments.each.with_index(1) do |comment, i| %>
    <tr>
    <td><%= i %>.  <%= comment.description %></td>
    <% if comment.user_id == current_user.id %>
      <td><%= link_to "Edit", edit_post_comment_path(@post.id, comment.id) %></td>
      <td><%= link_to "Delete", post_comment_path(@post.id,comment.id), method: 'delete', data: { confirm: "Are you Sure" } %></td>
    <% end %>
        </tr>
  <% end %>
</ul>
</table>